import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scope = '/manabi-sugoroku/';
const cachePrefix = 'metaborin/manabi-sugoroku/';
const generatedFiles = new Set(['sw.js', 'precache-manifest.json']);

function digest(content, encoding = 'hex') {
  return createHash('sha256').update(content).digest(encoding);
}

async function collectFiles(directory, relative = '') {
  const files = [];
  for (const entry of await readdir(join(directory, relative), { withFileTypes: true })) {
    const name = relative ? `${relative}/${entry.name}` : entry.name;
    if (entry.isSymbolicLink()) throw new Error(`PWA build does not follow symlinks: ${name}`);
    if (entry.isDirectory()) files.push(...await collectFiles(directory, name));
    else if (entry.isFile() && !generatedFiles.has(name)) files.push(name);
  }
  return files.sort();
}

function renderWorker({ version, assets }) {
  return `/* Generated by scripts/build-pwa.mjs. Complete build assets are installed together. */
const VERSION = ${JSON.stringify(version)};
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const CACHE = CACHE_PREFIX + VERSION;
const SCOPE = ${JSON.stringify(scope)};
const INDEX_URL = SCOPE + 'index.html';
const ASSETS = ${JSON.stringify(assets)};
const ASSET_URLS = new Set(ASSETS.map((asset) => new URL(asset.url, self.location.origin).href));

function belongsToApp(url) {
  return url.origin === self.location.origin && url.pathname.startsWith(SCOPE);
}

async function completeCache(cache) {
  const responses = await Promise.all(ASSETS.map((asset) => cache.match(asset.url)));
  return responses.every((response) => Boolean(response && response.ok));
}

async function offlineReady() {
  if (!(await caches.keys()).includes(CACHE)) return false;
  return completeCache(await caches.open(CACHE));
}

async function notifyReady() {
  const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  for (const client of windows) {
    if (belongsToApp(new URL(client.url))) {
      client.postMessage({ type: 'OFFLINE_READY', offlineReady: true, version: VERSION });
    }
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const existed = (await caches.keys()).includes(CACHE);
    try {
      const cache = await caches.open(CACHE);
      await cache.addAll(ASSETS.map((asset) => new Request(
        new URL(asset.url, self.location.origin).href,
        { cache: 'reload', integrity: asset.integrity }
      )));
      if (!(await completeCache(cache))) throw new Error('Offline cache is incomplete');
    } catch (error) {
      // A failed new installation must not leave a partial cache or remove an active one.
      if (!existed) await caches.delete(CACHE);
      throw error;
    }
    // Notification failure does not invalidate an otherwise complete installation.
    try { await notifyReady(); } catch { /* The page may have closed meanwhile. */ }
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // If storage was evicted after installation, preserve any older complete build.
    if (!(await offlineReady())) return;
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name !== CACHE && name.startsWith(CACHE_PREFIX))
      .map((name) => caches.delete(name)));
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'GET_OFFLINE_STATUS') return;
  if (event.source?.url && !belongsToApp(new URL(event.source.url))) return;
  const port = event.ports?.[0];
  if (!port) return;
  event.waitUntil((async () => {
    let ready = false;
    try { ready = await offlineReady(); } catch { /* Storage may be unavailable. */ }
    port.postMessage({ type: 'OFFLINE_STATUS', offlineReady: ready, version: VERSION });
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (!belongsToApp(url)) return;
  const navigation = request.mode === 'navigate';
  if (!navigation && !ASSET_URLS.has(url.href)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // These SRI-verified static files use the same canonical lookup as readiness checks.
    // A module request's Origin header must not miss a precache response with Vary: Origin.
    const response = await cache.match(navigation ? INDEX_URL : url.href);
    return response || fetch(request);
  })());
});
`;
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length && (args.length !== 2 || args[0] !== '--dist')) {
    throw new Error('Usage: node scripts/build-pwa.mjs [--dist <build-directory>]');
  }
  const directory = args.length ? resolve(args[1]) : resolve(dirname(fileURLToPath(import.meta.url)), '../dist');
  const names = await collectFiles(directory);
  for (const required of ['index.html', 'manifest.webmanifest']) {
    if (!names.includes(required)) throw new Error(`Missing required PWA build file: ${required}`);
  }
  const assets = await Promise.all(names.map(async (name) => {
    const contents = await readFile(join(directory, name));
    return {
      url: scope + name.split('/').map(encodeURIComponent).join('/'),
      bytes: contents.byteLength,
      integrity: `sha256-${digest(contents, 'base64')}`,
    };
  }));
  // Changing either an asset or the worker implementation yields a separate complete cache.
  const version = digest(JSON.stringify({ scope, cachePrefix, assets, worker: renderWorker.toString() }));
  const manifest = { version, totalBytes: assets.reduce((total, asset) => total + asset.bytes, 0), assets };
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  const manifestAsset = {
    url: `${scope}precache-manifest.json`,
    integrity: `sha256-${digest(manifestText, 'base64')}`,
  };
  await writeFile(join(directory, 'precache-manifest.json'), manifestText);
  await writeFile(join(directory, 'sw.js'), renderWorker({ version, assets: [...assets, manifestAsset] }));
  console.log(`PWA: ${assets.length} build files (${manifest.totalBytes} bytes), version ${version.slice(0, 12)}`);
}

await main();
